FROM golang:1.23.1-alpine3.20 as build
WORKDIR /app
COPY . /app
RUN go build -ldflags="-w -s" -o registryreplace cmd/registryreplace.go

FROM alpine:3.20
WORKDIR /app
COPY --from=build /app/registryreplace /app/registryreplace
COPY --from=build /app/cmd/etc /app/etc
ENTRYPOINT ["/app/registryreplace"]
