apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: registry-replace
spec:
  ports:
    - port: 443
      targetPort: 8443
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: default
  name: registry-replace
subsets:
  - addresses:
      - ip: 192.168.0.132
    ports:
      - port: 8443
