apiVersion: v1
kind: Namespace
metadata:
  name: admission
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: admission
  name: registry-replace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registry-replace
rules:
- apiGroups: [""]
  resources: ["services","configmaps","secrets"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: registry-replace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-replace
subjects:
- kind: ServiceAccount
  namespace: admission
  name: registry-replace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-replace
  namespace: admission
data:
  docker.io: docker.ketches.cn
  gcr.io: gcr.ketches.cn
  ghcr.io: ghcr.ketches.cn
  k8s.gcr.io: k8s-gcr.ketches.cn
  quay.io: quay.ketches.cn
  registry.k8s.io: k8s.ketches.cn
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: admission
data:
  registry_replace.yaml: |
    Name: "Registry-Replace"
    Host: "0.0.0.0"
    Port: 8443
    CertFile: "tls/server.crt"
    KeyFile: "tls/server.key"
    Log:
      Mode: "console"
      Encoding: "json"
      Level: "info"
      Compress: true
    IncludeNamespaces:
      - "*"
    ExcludeNamespaces:
      - "kube-node-lease"
      - "kube-public"
      - "kube-system"
      - "admission"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: admission
  name: registry-replace
  labels:
    app: registry-replace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-replace
  template:
    metadata:
      labels:
        app: registry-replace
    spec:
      serviceAccountName: registry-replace
      restartPolicy: Always
      containers:
      - name: webhook
        image: docker.ketches.cn/cting/registry-replace:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: app-config
          mountPath: /etc/registry-replace
      volumes:
      - name: app-config
        configMap:
          name: app-config
          items:
          - key: registry_replace.yaml
            path: registry_replace.yaml
