// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type AdmissionRequest struct {
	UID       string                 `json:"uid"`
	Kind      *Object                `json:"kind"`
	Resource  *Object                `json:"resource"`
	Operation string                 `json:"operation"`
	Object    map[string]interface{} `json:"object,optional"`
}

type AdmissionResponse struct {
	UID       string `json:"uid"`
	Allowed   bool   `json:"allowed"`
	Patch     []byte `json:"patch,omitempty"`
	PatchType string `json:"patchType,omitempty"`
}

type AdmissionReview struct {
	Kind       string             `json:"kind,omitempty"`
	APIVersion string             `json:"apiVersion,omitempty"`
	Request    *AdmissionRequest  `json:"request,omitempty"`
	Response   *AdmissionResponse `json:"response,omitempty,optional"`
}

type Object struct {
	Group    string `json:"group"`
	Version  string `json:"version"`
	Kind     string `json:"kind,omitempty,optional"`
	Resource string `json:"resource,omitempty,optional"`
}

type Request struct {
}

type Response struct {
	Pong string `json:"pong"`
}
